;;; post-init.el --- Post Init -*- lexical-binding: t; -*-

;; Probably a security issue
(setq package-check-signature nil)

(add-to-list 'load-path "~/.emacs.d/lisp")
(load "+compile-angel.el")

(load "+straight.el")
(load "+icons.el")
;; (load "+dashboard.el")
(load "+theme.el")
(load "+keybindings.el")
(load "+tree-sitter.el")
(load "+copilot.el")
(load "+gptel.el")
(load "+evil.el")
(load "+term.el")
(load "+projectile.el")
(load "+helm.el")
(load "+magit.el")
(load "+hl-todo.el")
(load "+flycheck.el")
(load "+which-key.el")
(load "+treemacs.el")
(load "+modeline.el")
(load "+ace-window.el")
(load "+yasnippet.el")
(load "+lsp.el")
(load "+corfu.el")
(load "+vundo.el")
(load "+prettier.el")
(load "+git-gutter.el")
(load "+smartparens.el")
(load "+minibuffer.el")
(load "+dired.el")
