;;; post-init.el --- Post Init -*- lexical-binding: t; -*-

;; Probably a security issue
(setq package-check-signature nil)

(add-to-list 'load-path "~/.emacs.d/lisp")
(load "+compile-angel.el")

(eval-when-compile (require 'use-package))

(load "+org")
(load "+agenda")
(load "+org-modern.el")
(load "+evil")
(load "+keybindings")
(load "+icons")
;; (load "+dashboard.el")
(load "+theme")
(load "+tree-sitter")
(load "+copilot")
(load "+gptel")
(load "+term")
(load "+projectile")
(load "+helm")
(load "+magit")
(load "+hl-todo")
(load "+flycheck")
(load "+which-key")
(load "+treemacs")
(load "+modeline")
(load "+ace-window")
(load "+yasnippet")
(load "+lsp")
(load "+lsp-ui")
(load "+corfu")
(load "+vundo")
(load "+prettier")
(load "+git-gutter")
(load "+minibuffer")
(load "+dired")
(load "+indent")
(load "+go")
(load "+activities")
(load "+orderless")
(load "+editor")
(load "+docker")
(load "+git-timemachine")
(load "+markdown")
(load "+protobuf")
(load "+dape")

(load "secrets")
